### ISSUE TITLE
Make ssl certificate generation optional (for usage behind reverse proxy) 

### ISSUE THREAD

**Issue by fbartels** [subspacecloud/subspace#1]
Hi,

this looks like a useful project, exposing just a plain http would allow to run subspace behind apache/nginx/caddy..

**Comment by heliostatic** [comment]
Yes, this would be great for mixed environments where ssl cert generation is already being handled.

**Comment by LickABrick** [comment]
Would be great to have this feature since I run everything behind a reverse proxy which manages my certificates.

**Comment by BankaiNoJutsu** [comment]
You can check out my fork.
https://github.com/BankaiNoJutsu/subspace

basically I changed some things like:
- Added QR code
- http or https (not tested with docker sorry)
- Editable email settings
- very buggy status page
- too simplistic duckdns updater.

**Comment by fbartels** [comment]
Hi @BankaiNoJutsu,

thanks for trying to keep this repo alive. But why did you remove the license file in https://github.com/BankaiNoJutsu/subspace/commit/ad549f67b603993f8628f43ebdc71ed4dac92ffc ?

**Comment by BankaiNoJutsu** [comment]
Hi @fbartels, actually that's a mistake. I never intended to change the license or anything. It's free for all.

Will add it back. I'm dirty coding, so mistakes happen :)

**Comment by moookino** [comment]
@BankaiNoJutsu will you plan to update docker image?

**Comment by BankaiNoJutsu** [comment]
@moookino sorry not planned. but feel free to adapt and make a pull :)

**Comment by jacotec** [comment]
Even with port 80 also forwarded through my HAPROXY for the subdomain I have no luck. Port 443 does not work, I can open a TCP connection to it, but even the health check of my HAPROXY (without checking the certificate) returns a SSL handshake error.

Something seems not to work here.

I'd be very interested to run @BankaiNoJutsu 's fork ... but is there a doc how to get this fork up and running? The README references to the standard docker image, and checking out your repo and run a "go build" in it returns nothing but a bunch of errors about missing references (Ubuntu 16.04 with latest golang package).

Any help is highly appreciated.

**Comment by BankaiNoJutsu** [comment]
@jacotec Hey, you can try the install or build script in the "scripts" folder. What errors do you get?

**Comment by Fastidious** [comment]
@BankaiNoJutsu many errors. The script will download `go`, even though it is already installed on the system. I tried it on a vanilla Ubuntu VM, and got:

```
root@vanilla-vm:/tmp/wg/subspace-master/scripts# ./build.sh -i -d example.net -p 8080
> Stopping service
Failed to stop subspace.service: Unit subspace.service not loaded.
> Setting GO Path to: /tmp/wg/subspace-master/scripts
> Actual arch is: amd64
> Actual go version is: go version go1.11.5 linux/amd64
> GO is already installed to /usr/local
> Running go get
github.com/jteeuwen/go-bindata (download)
github.com/dustin/go-humanize (download)
github.com/julienschmidt/httprouter (download)
github.com/Sirupsen/logrus (download)
Fetching https://golang.org/x/sys/unix?go-get=1
Parsing meta tags from https://golang.org/x/sys/unix?go-get=1 (status code 200)
get "golang.org/x/sys/unix": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
Fetching https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
golang.org/x/sys (download)
github.com/gorilla/securecookie (download)
Fetching https://golang.org/x/crypto/acme/autocert?go-get=1
Parsing meta tags from https://golang.org/x/crypto/acme/autocert?go-get=1 (status code 200)
get "golang.org/x/crypto/acme/autocert": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/acme/autocert?go-get=1
get "golang.org/x/crypto/acme/autocert": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
Fetching https://golang.org/x/time/rate?go-get=1
Parsing meta tags from https://golang.org/x/time/rate?go-get=1 (status code 200)
get "golang.org/x/time/rate": found meta tag get.metaImport{Prefix:"golang.org/x/time", VCS:"git", RepoRoot:"https://go.googlesource.com/time"} at https://golang.org/x/time/rate?go-get=1
get "golang.org/x/time/rate": verifying non-authoritative meta tag
Fetching https://golang.org/x/time?go-get=1
Parsing meta tags from https://golang.org/x/time?go-get=1 (status code 200)
golang.org/x/time (download)
Fetching https://go.uber.org/zap?go-get=1
Parsing meta tags from https://go.uber.org/zap?go-get=1 (status code 200)
get "go.uber.org/zap": found meta tag get.metaImport{Prefix:"go.uber.org/zap", VCS:"git", RepoRoot:"https://github.com/uber-go/zap"} at https://go.uber.org/zap?go-get=1
go.uber.org/zap (download)
Fetching https://go.uber.org/atomic?go-get=1
Parsing meta tags from https://go.uber.org/atomic?go-get=1 (status code 200)
get "go.uber.org/atomic": found meta tag get.metaImport{Prefix:"go.uber.org/atomic", VCS:"git", RepoRoot:"https://github.com/uber-go/atomic"} at https://go.uber.org/atomic?go-get=1
go.uber.org/atomic (download)
Fetching https://go.uber.org/multierr?go-get=1
Parsing meta tags from https://go.uber.org/multierr?go-get=1 (status code 200)
get "go.uber.org/multierr": found meta tag get.metaImport{Prefix:"go.uber.org/multierr", VCS:"git", RepoRoot:"https://github.com/uber-go/multierr"} at https://go.uber.org/multierr?go-get=1
go.uber.org/multierr (download)
Fetching https://gopkg.in/gomail.v2?go-get=1
Parsing meta tags from https://gopkg.in/gomail.v2?go-get=1 (status code 200)
get "gopkg.in/gomail.v2": found meta tag get.metaImport{Prefix:"gopkg.in/gomail.v2", VCS:"git", RepoRoot:"https://gopkg.in/gomail.v2"} at https://gopkg.in/gomail.v2?go-get=1
gopkg.in/gomail.v2 (download)
github.com/jasonlvhit/gocron (download)
> Running go-bindata
./build.sh: line 132: ./bin/go-bindata: No such file or directory
can't load package: package .: no Go files in /tmp/wg/subspace-master/scripts
can't load package: package .: no Go files in /tmp/wg/subspace-master/scripts
> Building subspace
can't load package: package .: no Go files in /tmp/wg/subspace-master/scripts
```

**Comment by stkac** [comment]
@BankaiNoJutsu no idea how ported it to Docker but I need, do you know how start it?

thanks in advance,

**Comment by fbartels** [comment]
@subspacecloud with the ticket being closed does that mean that you are not interested in this feature or that this will be included in the code you want to push "soon" (as indicated in https://news.ycombinator.com/item?id=19709780)?

**Comment by jacotec** [comment]
@fbartels I was about to ask the same ... saw the ticket closed without any comment and no new version, not sure if there is any future of this project. A pity, it did look not bad ...

**Comment by anoma** [comment]
Just to feedback that this decision is putting people off the project both in terms of the technical reasoning to arbitrarily enforce the use of SSL and the way the ticket was closed with no discussion.

I doubt this was you intention and you may not be aware of the impact but people are finding the project, finding this ticket and then abandoning it.

**Comment by jacotec** [comment]
It's already implemented and working fine with the Docker image @anoma

**Comment by anoma** [comment]
This is great news but a lesson in the need for proper ticket documentation. To the causal observer this ticket reads as WONTFIX.

Thanks all.
