### ISSUE TITLE
trouble with --datadir argument

### ISSUE THREAD

**Issue by ebdavison** [subspacecloud/subspace#12]
when specifying --datadir to be some place other than "/data", the application still tries to read/write to "/data/..." and does not fully respect the directory.
Also, when using --datadir, subdirectories are not created automatically and I get errors about being unable to open files.

```
$ sudo ./subspace-linux-amd64 --http-host subsapce.example.com --datadir /opt/subspace
INFO[0000] Subspace version: b84ee3e                    
INFO[0000] Subspace version: b84ee3e https://subspace.example.com/ 
INFO[0011] 1556568804 "" GET "/" 188 ms                 
WARN[0016] command failed: exit status 1
+ cd /data/wireguard
/bin/bash: line 6: cd: /data/wireguard: No such file or directory 
INFO[0016] 1556568809 "" POST "/profiles/add" 343 ms    
INFO[0016] 1556568809 "" GET "/?error=addprofile" 54 ms 
^C
$ ls -al /opt/subspace/
total 4
drwxr-xr-x  4 root root   58 Apr 29 20:13 .
drwxr-xr-x. 6 root root   82 Apr 29 18:30 ..
-rw-r--r--  1 root root 1184 Apr 29 20:13 config.json
drwx------  2 root root   59 Apr 29 19:13 letsencrypt
drwxr-xr-x  2 root root    6 Apr 29 19:17 wireguard

```

**Comment by Fastidious** [comment]
Yes, that's somewhere in `handlers.go`. I don't like that calls to bash either, but I guess it works...

**Comment by subspacecloud** [comment]
Fixed the /data issues, that was just a mistake in a couple places where it was hardcoded instead of sent as a template variable. Thanks for pointing it out.

And yes, the bash calls will be replaced in a future version but they should be safe/correct in that errexit is set properly and return codes are checked.
