### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Fastidious** [subspacecloud/subspace#16]
Running `Subspace 73e6d10`. I create the admin account (web), but then I can't login. The `config.json` gets created properly (nothing else is created on the `datadir`, just the `config.json` file). My command line to start subspace:

```subspace -letsencrypt=false --http-host host.example.com -datadir /var/subspace -http-addr:8888```

**Comment by subspacecloud** [comment]
Thanks for the report. It may be that you need to add `-http-insecure=true` to enable session cookies over HTTP (non-HTTPS). This option was added for users that want to use Subspace with plaintext HTTP which is only recommended on a private LAN or over a VPN. Normally you should run it behind an HTTPS proxy or standalone with Let's Encrypt using HTTPS.

If that doesn't fix the issue, please post the log output. Thanks!

**Comment by Fastidious** [comment]
@subspacecloud thank you for replying. It was my fault, actually. I misspelled the `--http-host` and that was causing the problem. Closing.
