### ISSUE TITLE
Request: Add support for split routing?

### ISSUE THREAD

**Issue by jnsgruk** [subspacecloud/subspace#26]
Hi,

First of all great project, thank you.

Would it be possible to add some configuration to the devices such that they don't always route all traffic through the tunnel? Currently "AllowedIPs" is set to "0.0.0.0" - it would be nice if there was an option to disable that and only send VPN subnet traffic down the tunnel..

Thanks,

Jon

**Comment by jasonehines** [comment]
@jnsgruk if you change your 'Allowed IPs' on the client to `10.99.97.0/22, fd00::10:97:0/112` it will only route the vpn subnet traffic through wireguard.

**Comment by jnsgruk** [comment]
Hey, yep understood, just thought it might make a neat feature for newer users to be able to specify that easily in the UI :)
