### ISSUE TITLE
Feature request: SSO

### ISSUE THREAD

**Issue by evaryont** [subspacecloud/subspace#3]
This is a tracking issue, reflecting the comments in /r/selfhosted. 

It would be awesome to support some sort of authentication delegation. I can see 3 options:

1. LDAP support
2. OpenID Connect/SAML support
3. Trusting REMOTE_USER, etc HTTP headers from a reverse proxy

My personal preference would 2 or 3, allowing me to backhaul authentication to Keycloak. 3 may be the easiest, especially after the work to allow disabling TLS generation.

**Comment by grugnog** [comment]
@evaryont I think 3 sounds like a great place to start to me - works for the simplest basic auth case, and there are plenty of options for OAuth/OpenID proxies also. Would the devices/keys then just be namespaced/filtering when a user is present?

**Comment by evaryont** [comment]
Yeah. I'm not sure what the authorization scheme would be like nor what plans @subspacecloud has in that regard.

My initial thoughts though are merely limiting access from random people, and that everyone is trusted. Pretty similar to the current model as shown in the [signinHandler function](https://github.com/subspacecloud/subspace/blob/master/handlers.go#L173).

All of this might have to be revisited if something like multitenacy is ever desired.

**Comment by subspacecloud** [comment]
Added very simple SAML support to the new version. It seems to work pretty well with Google and Okta which are the two services I have easy access to. Happy to test with other providers if there are issues but it should work if they're similar to Google/Okta.

Basic instructions are included in the Settings page.

Thanks!
