### ISSUE TITLE
Permission denied (you must be root) Perhaps iptables or your kernel needs to be upgraded.

### ISSUE THREAD

**Issue by 101script** [subspacecloud/subspace#31]
hi, i using cockpit project to administration my dockers, in system i logged as root!
i downloaded docker and setting on this mode:
![image](https://user-images.githubusercontent.com/52635636/60974809-713d1980-a333-11e9-82ab-c5d64010beab.png)
console output:
 SUBSPACE_BACKLINK=
+ '[' -z '' ']'
+ export SUBSPACE_LETSENCRYPT=true
+ SUBSPACE_LETSENCRYPT=true
+ '[' -z '' ']'
+ export SUBSPACE_HTTP_ADDR=:80
+ SUBSPACE_HTTP_ADDR=:80
+ '[' -z '' ']'
+ export SUBSPACE_HTTP_INSECURE=false
+ SUBSPACE_HTTP_INSECURE=false
+ export NAMESERVER=1.1.1.1
+ NAMESERVER=1.1.1.1
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ echo 'nameserver 1.1.1.1'
+ /sbin/iptables -t nat --check POSTROUTING -s 10.99.97.0/24 -j MASQUERADE
iptables v1.6.1: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
+ /sbin/iptables -t nat --append POSTROUTING -s 10.99.97.0/24 -j MASQUERADE
iptables v1.6.1: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
after running, i received this error, how to fix it? best regards

**Comment by Fastidious** [comment]
@101script I might be wrong, but I think your question goes beyond the scope of "regular use" for the application. The owner(s) doesn't seem to active, so the hope for an answer diminishes.

That being said, I know nothing about Cockpit, but to setup `subspace` you must be root, or have root privileges.

**Comment by 101script** [comment]
ok, i can install it without docker container? directly to server?

**Comment by Fastidious** [comment]
@101script as is now, you can't. Well, you can, but will run into hurdles. If you are willing to deal with those...
