### ISSUE TITLE
ip6tables v1.6.1 can't initialize 

### ISSUE THREAD

**Issue by Semetra22** [subspacecloud/subspace#35]
At first, the container ran smoothly. After restarting the host, subspace could no longer be started.

<pre> <code>ip6tables v1.6.1: can't initialize ip6tables table nat': Table does not exist (do you need to insmod?) <br> Perhaps ip6tables or your kernel needs to be upgraded.</code> </pre>

Creating a new container brings the same error.
Any ideas?

**Comment by zarlo** [comment]
im getting this too, tryed to reinstall on a fresh VM and i still get the same

**Comment by zarlo** [comment]
o i forgot to add 
iptable_nat
ip6table_nat
to /etc/modules

**Comment by zarlo** [comment]
^^^ @Semetra22  that should fix it for you too

**Comment by Semetra22** [comment]
@zarlo Thanks! Worked for me.
