### ISSUE TITLE
Freebsd compile error

### ISSUE THREAD

**Issue by zhongshanliyu** [subspacecloud/subspace#53]
got below errror when compile Freebsd12.1

`/go/subspace # go build
# _/root/go/subspace
./handlers.go:25:20: samlSP.GetAuthorizationToken undefined (type *samlsp.Middleware has no field or method GetAuthorizationToken)
./handlers.go:30:8: samlSP.RequireAccountHandler undefined (type *samlsp.Middleware has no field or method RequireAccountHandler)
./web.go:190:22: samlSP.GetAuthorizationToken undefined (type *samlsp.Middleware has no field or method GetAuthorizationToken)
./web.go:191:23: undefined: samlsp.WithToken
root@dev:~/go/subspace # go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build364017682=/tmp/go-build -gno-record-gcc-switches"
`

**Comment by zhongshanliyu** [comment]
go version go1.13.1 freebsd/amd64

**Comment by russlevy** [comment]
I'm receiving the same on Ubuntu 18.04

**Comment by zhongshanliyu** [comment]
I remove samlSP code then passed compile.
