### ISSUE TITLE
Impossible to disable ipv6

### ISSUE THREAD

**Issue by theonlydoo** [subspacecloud/subspace#71]
Subspace's docker container have no documented option to disable ipv6. Default values on a host with explicitely disabled ipv6 are making the container crash:

```shell
+ ip addr add fd00::10:97:1/112 dev wg0
RTNETLINK answers: Permission denied
```

**Comment by Fastidious** [comment]
This repository is hibernating. Use https://github.com/subspacecommunity/subspace.

**Comment by theonlydoo** [comment]
https://github.com/subspacecommunity/subspace/issues/78
