### ISSUE TITLE
http-insecure ignored

### ISSUE THREAD

**Issue by theonlydoo** [subspacecloud/subspace#72]
while running:

```bash
$ subspace -datadir /data   -http-insecure -http-addr 127.0.0.1:80 -http-host foo.bar.baz
INFO[0000] Subspace version: 207b0aa https://foo.bar.baz/ 
```

a curl shows me that subspace doesnt give a crap about my flag
```
$ curl 127.1 -i
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: https://foo.bar.baz/
Date: Wed, 27 May 2020 10:06:09 GMT
Content-Length: 43

<a href="https://foo.bar.baz/">Found</a>.
```

**Comment by Fastidious** [comment]
This repository is hibernating. Use https://github.com/subspacecommunity/subspace.

**Comment by theonlydoo** [comment]
is it possible to disable issue opening then? 

migrated here with the right version: https://github.com/subspacecommunity/subspace/issues/77

**Comment by Fastidious** [comment]
@theonlydoo I would if I could. I am not the owner of the repository.
