### ISSUE TITLE
Need some more documentation

### ISSUE THREAD

**Issue by dasche** [subspacecloud/subspace#8]
Tried to run subspace without any luck on ubuntu 18.10. How to access the UI after running?

**Comment by rvpn** [comment]
> Tried to run subspace without any luck on ubuntu 18.10. How to access the UI after running?

did you still having problem on this issue? I have no problem running it on DO / GC server with ubuntu 16.04.

you can access your own web UI with the domain name you have provided like mine 

https://subspace.wyreguard.gq/

**Comment by Fastidious** [comment]
@rvpn care to share the init script you are using to start up subspace? I am not using Docker.

**Comment by rvpn** [comment]
> @rvpn care to share the init script you are using to start up subspace? I am not using Docker.

im not using subspace anymore,

maybe this link might help you 

https://raw.githubusercontent.com/atrandys/wireguard/master/wireguard_web.sh

it's from https://www.atrandys.com/2019/1681.html
